### ISSUE TITLE
Quest 2 not supported?

### ISSUE THREAD

**Issue by theburning** [korejan/ALVR#103]
I download nightly builds of the quest app two nights in a row and even tried the debug version. I know how useless "doesn't work" is as a bug report, but there's not much more I can provide then I launch the app, the screen turns cyan, and... well, that's it. I've used the non-forked ALVR and I know the cyan screen is unexpected. I can't even find anything about this issue by googling, so... is Quest 2 just no longer supported and nobody bothered to update the page?

**Comment by korejan** [comment]
Hello, alxr currently does not have any client-side side UI/lobby screen (but it's coming), what you're seeing is what it looks like when there's no connection.

Make sure you're using the server builds from the same page as where you got the client, by default there is a client discovery system and inorder for that to work is it's not blocked by firewall and on windows, windows network discovery is enabled.

When it is works the client should show up in the server's new clients list, in the connection tab you need to click on the trust button. Alternatively you can manually add the client there.

**Comment by theburning** [comment]
Ah! I understand now. So all the settings are done on the server? I'm trying to figure out how to get the passthrough working. I managed to get handtracking working. Not perfect, but what is.

**Comment by korejan** [comment]
Not everything there are some client-side properties but as there is no UI currently so it's not easy/obvious how to set them for android platforms.

To toggle on the passthrough modes it's:
- Menu + A for simple blend mode
- Menu + B for masking

Note in the current build the chroma-keying shader hardcodes the key / thresholds, this is again because of lack of UI and is part of the reason why I'm adding client-side UI (among other settings).

[Here's](https://streamable.com/5yxtdd) (skip to ts=0.29s) a WIP video of what to expect with client-side UI and configurable passthrough modes with the upcoming changes (also note this is not what the final UI will look like). 

Right now it's on a bit of pause while I focus on on sorting the video stream quality/resolutions and better scaling to much higher resolutions when I'm done with that I will  go back to wrapping up the UI work too.
