### ISSUE TITLE
Warping View (Quest 2)

### ISSUE THREAD

**Issue by ducko0** [korejan/ALVR#44]
When rotating HMD the view is warped/distorted in a weird way. Almost like its shifting depth.

I have followed all wiki instructions and foveated encoding is disabled in the dashboard.

I am using a Quest 2 with alxr-client v0.0.10, it happens using the quest client apk aswell as the windows client (connected using Oculus Link).

It does not happen when using the regular ALVR client.

**Comment by ducko0** [comment]
I did some further testing and found that this issue is likely caused by the alxr-client sending the incorrect view config data to steam.

I figured this out by editing the source code of the ALVR server and logging the differences in the view config data received connecting using the alxr vs the alvr client. I found that they both sent different eye fov configs (ipd was the same). So I then edited the code for the server and made it manually set the fov configs I got from the logs of the alvr client and connected using the alxr client. 

This managed to fix the warping/distortion and alxr is much more usable now however, I now notice that the transforms on the controllers are about 5 cm off the IRL position and they are also scaled much smaller. Maybe it is sending incorrect info for this too?

Still not sure what exactly is causing this to happen in the alxr-client code, I have never done any coding in C++ before today and I also don't really understand much about how VR streaming software or OpenXR work so all this info could be very wrong. All I know is that changing view configs at least partially fixes the issue.

**Comment by korejan** [comment]
> I did some further testing and found that this issue is likely caused by the alxr-client sending the incorrect view config data to the server.
> 
> I figured this out by editing the source code of the ALVR server and logging the differences in the view config data received connecting using the alxr vs the alvr client. I found that they both sent different eye fov configs (ipd was the same). So I then edited the code for the server and made it manually set the fov configs I got from the logs of the alvr client and connected using the alxr client.
> 
> This managed to fix the warping/distortion and alxr is much more usable now however, I now notice that the transforms on the controllers are about 5 cm off the IRL position and they are also scaled much smaller. Maybe it is sending incorrect info for this too?
> 
> Still not sure what exactly is causing this to happen in the alxr-client code, I have never done any coding in C++ before today and I also don't really understand much about how VR streaming software or OpenXR work so all this info could be very wrong. All I know is that changing view configs at least partially fixes the issue.
> 
> edit: oh and 2 other things i noticed.
> 
>     1. the view config data that is logged on alxr windows client differs from both the ones I got from my logging of the alvr server.
> 
>     2. the "RecommendedRenderTargetSize" and "EyeOutputViewport" recived by the server using alxr is also smaller than the one i got using alvr.

Huh, that interesting, as this does not happen with other OpenXR runtimes/headsets so I assumed it was either a bug in Meta's implementation of `xrLocateView/Space` with future times or reprojection is being applied based on using the matched view poses with the final decode frame being slightly behind in the time compared to the actual current pose and the runtime intenerally is comparing them to know when to apply it.

About the resolutions, alxr sends the the recommend eye resolution [obtained](https://registry.khronos.org/OpenXR/specs/1.0/man/html/XrViewConfigurationView.html) from the OpenXR runtime, the ALVR client uses a VrAPI function to get the native display resolution, depending on the runtime these typically aren't equilvant and the recommend res from the runtime is generally smaller than native display resolution.

I stick with the OpenXR way because trying obtain a native display res will end up being platform specific or even not possible. So I stick with the simplier solution of just accepting but the user can always override this by either uping the percentage and/or fixed pixel sizes in the ALVR dashboard.

Anyway this is very useful info I will look into, thanks for trying to look into it.

**Comment by korejan** [comment]
@ducko0 This is now [fixed](https://github.com/korejan/ALVR/commit/8a304999e8ecd11179b384d90532a253d28ad01b), you can try the latest nightly [build](https://github.com/korejan/ALXR-nightly/releases/tag/v0.10.0%2Bnightly.2022.10.08)

Thank you for taking the time look into this and leading my in the right direction, you was spot on. It looks like either VrApi or SteamVR use different conventions from OpenXR, the difference was ALVR client sends the bottom & top fov angles swapped & negated.

The controllers being off by 5c.m. wont be a problem in this fix, it was happening to you because of using the values from the ALVR client, the angles are actually being rounded up by a few decimal points (4 or 5 I don't remember) but it even this small amount has an effect. The fix does not have this issue.

I will credit you in the next offical release, thanks again.
