### ISSUE TITLE
pico sdk updated Version：v2.1.0 , now support pico4. 

### ISSUE THREAD

**Issue by happychui** [korejan/ALVR#71]
pico sdk has been update to v2.1.0 , I think it's time to update sdk. Better support pico4.

**Comment by korejan** [comment]
@happychui Hello, yes I've done this already including support for passthrough modes and fixes, I just haven't pushed it to github yet because I wanted to also change how the defaults resolutions at relative 100% work. If you want to can test this [build ](https://drive.google.com/file/d/1zI5byTzAMat8QrJoKwGhGVUmaeW7pxch/view?usp=share_link) with the those changes

**Comment by korejan** [comment]
@happychui just to let you know I've push my changes now and new builds will be available later today.
